# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Documentation

on:
  push:
    branches: [ master, build ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
      uses: actions/setup-python@v2
      with:
        python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
    - name: setup
      run: |
        sudo apt install pandoc
        pip install -r requirements.txt
        pip install .[doc]
    - name: Build docs
      run: |
        doit -n 2 pdf book
    - uses: actions/upload-artifact@v2
      with:
        name: {{cookiecutter.name}} pdf
        path: _build/pdf/book.pdf
